[package]
name = "lnmai-core"
version = "0.1.0"
edition = "2024"

[lib]
name="liblnmai"
crate-type = ["cdylib", "rlib"]

# in /Users/pingfanh/project/Mai2Chart/demo/macroquad_sim/lnmai-core-ffi/Cargo.toml


[build-dependencies]
cc = "1"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libloading = "0.9.0"
lean-sys = {version =  "0.0.9",path="./lean-sys",features = [] }